package utils;

/**
 * Created by elainemnkubitu on 11/11/18.
 */
public enum ServiceList {
    CATERING, BAKERYNEEDS, PHOTOGRAPHY, TRANSPORT, DECORDESIGN, VENUE, STYLING, DRESSING,
    RELIGIOUSCEREMONIES,EMCEE,ENTERTAINMENT,TENTSCAMPNING,ACCOMMODATION

}
